language: python
env:
  global:
    - CI=true

matrix:
  include:
    - os: linux
      python: 3.5
      addons:
        apt_packages:
          - pandoc
    - os: linux
      python: 3.4
      addons:
        apt_packages:
          - pandoc
    - os: osx
      language: generic
      sudo: false
  allow_failures:
    - os: osx
      language: generic
      sudo: false

install:
    - chmod u+x travis/install.sh
    - travis/install.sh
    - pip3 --version

script:
    - make sample_data
    - make responses
    - make scales
    - make json
    - make plots
    - make web
    # - make all
    - py.test

notifications:
    email: false
